id: P9965DAAE
initial_creation_type: ocr
source_metadata:
  volumes:
    c4f508d253124c3f8ecc2a0083232db6:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བཀྲ་ཤིས་ཀྱི་ཚིགས་སུ་བཅད་པ།
      total_pages: 1880
      volume_number: 116
